<template>
<div class="container">
      <!-- Footer -->
  <b-footer type="dark" variant="info" class="page-footer font-small pt-4 mt-4">
    <b-container class="text-left">
      <b-row>
        <b-col md="5">
          <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Khelo Lottery</h5>
          <p>It is an online application to buy lottery and clain rewards.</p>
        </b-col>
        <hr class="clearfix w-100 d-md-none" />
        <b-col md="2">
          <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">Quick Links</h5>
          <ul class="list-unstyled">
            <li><a href="#!">Cart</a></li>
            <li><a href="#!">Clain</a></li>
            <li><a href="#!">Results 3</a></li>
            <li><a href="#!">Contact Us</a></li>
          </ul>
        </b-col>
        <hr class="clearfix w-100 d-md-none" />
        <b-col md="2">
          <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">INFORMATION</h5>
          <ul class="list-unstyled">
            <li><a href="#!">Login </a></li>
            <li><a href="#!">Signup</a></li>
            <li><a href="#!">Blog</a></li>
            <li><a href="#!">Contact Us</a></li>
          </ul>
        </b-col>
        <hr class="clearfix w-100 d-md-none" />
        <b-col md="3">
          <h5 class="text-uppercase mb-4 mt-3 font-weight-bold">CONTACT US</h5>
          <ul class="list-unstyled">
            <li>Location: 2750 Quadra Street Victoria, Canada</li>
            <li>Call Us: (+123) 456-7898</li>
            <li>Email Us: support@bolster.com</li>
            <li>Fax: +123456</li>
          </ul>
        </b-col>
      </b-row>
    </b-container>
    <hr />
    <div class="text-center py-3">
      <ul class="list-unstyled list-inline mb-0">
        <li class="list-inline-item">
          <h5 class="mb-1">Register for free</h5>
        </li>
        <li class="list-inline-item"><a href="#" class="btn btn-danger btn-rounded">Sign up!</a></li>
      </ul>
    </div>
    <hr />
    <div class="text-center">
      <ul class="list-unstyled list-inline">
        <li class="list-inline-item"><a class="btn-floating btn-sm btn-fb mx-1"><i class="fa fa-facebook"> </i></a></li>
        <li class="list-inline-item"><a class="btn-floating btn-sm btn-tw mx-1"><i class="fa fa-twitter"> </i></a></li>
        <li class="list-inline-item"><a class="btn-floating btn-sm btn-gplus mx-1"><i class="fa fa-google-plus"> </i></a></li>
        <li class="list-inline-item"><a class="btn-floating btn-sm btn-li mx-1"><i class="fa fa-linkedin-in"> </i></a></li>
        <li class="list-inline-item"><a class="btn-floating btn-sm btn-dribbble mx-1"><i class="fa fa-dribbble"> </i></a></li>
      </ul>
    </div>
    <div class="footer-copyright text-center py-3">
      <b-container fluid>
        &copy; 2020 Copyright: <a href="https://www.KehloLottery.com"> ManjotSingh.com </a>
      </b-container>
    </div>
  </b-footer>
</div>
</template>